package com.huan.HTed.cado.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "cado_catalog")
public class Catalog extends BaseDTO {

     public static final String FIELD_CATALOG_ID = "catalogId";
     public static final String FIELD_CATALOG_NAME = "catalogName";


     @Id
     @GeneratedValue
     private Long catalogId;

     @NotEmpty
     @Length(max = 45)
     private String catalogName;


     public void setCatalogId(Long catalogId){
         this.catalogId = catalogId;
     }

     public Long getCatalogId(){
         return catalogId;
     }

     public void setCatalogName(String catalogName){
         this.catalogName = catalogName;
     }

     public String getCatalogName(){
         return catalogName;
     }

     }
