package com.huan.HTed.cado.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "cadoexcel_orders")
public class Orders extends BaseDTO {

     public static final String FIELD_ORDER_NO = "orderNo";
     public static final String FIELD_B_BRANCH_NAME = "bBranchName";
     public static final String FIELD_C_MERCHANT_NAME = "cMerchantName";
     public static final String FIELD_D_AUTHORIZED_OPERATOR = "dAuthorizedOperator";
     public static final String FIELD_E_MARKETING_PERSONNEL_CODE = "eMarketingPersonnelCode";
     public static final String FIELD_F_RECOMMENDED_PERSONNEL_CODE = "fRecommendedPersonnelCode";
     public static final String FIELD_G_CUSTOMER_NAME = "gCustomerName";
     public static final String FIELD_H_CARD_LAST_FOUR_NUMBER = "hCardLastFourNumber";
     public static final String FIELD_I_CERTIFICATES_LAST_FIVE_NUMBER = "iCertificatesLastFiveNumber";
     public static final String FIELD_J_CONTACT_NUMBER = "jContactNumber";
     public static final String FIELD_K_TELPHONE = "kTelphone";
     public static final String FIELD_L_DELIVERY_ADDRESS = "lDeliveryAddress";
     public static final String FIELD_M_ZIP_CODE = "mZipCode";
     public static final String FIELD_N_INVOICE_HEADER = "nInvoiceHeader";
     public static final String FIELD_O_COMMODITY_NUMBER = "oCommodityNumber";
     public static final String FIELD_P_COMMODITY_PRICE = "pCommodityPrice";
     public static final String FIELD_Q_APPLICATION_NUMBER = "qApplicationNumber";
     public static final String FIELD_R_AUTHORIZATION_CODE = "rAuthorizationCode";
     public static final String FIELD_S_PRODUCT_NUMBER = "sProductNumber";
     public static final String FIELD_T_CUSTOMER_ORDER_DATE = "tCustomerOrderDate";
     public static final String FIELD_U_ACTUAL_DELIVERY_DATE = "uActualDeliveryDate";
     public static final String FIELD_V_COURIER_NUMBER = "vCourierNumber";
     public static final String FIELD_W_COURIER_SERVICES_COMPANY = "wCourierServicesCompany";
     public static final String FIELD_X_OVERDUE_MARK = "xOverdueMark";
     public static final String FIELD_Y_DELIVERY_FILE_CATEGORY = "yDeliveryFileCategory";
     public static final String FIELD_Z_CARD_PRODUCT = "zCardProduct";
     public static final String FIELD_AA_NAME_OF_AGENT = "aaNameOfAgent";
     public static final String FIELD_AB_TELPHONE_OF_AGENT = "abTelphoneOfAgent";
     public static final String FIELD_AC_ORDER_STATUS = "acOrderStatus";
     public static final String FIELD_AD_BZ = "adBz";
     public static final String FIELD_AL_BANK_FEEDBACK_TIME = "alBankFeedbackTime";
     public static final String FIELD_AM_BANK_FEEDBACK_TYPE = "amBankFeedbackType";
     public static final String FIELD_AN_BANK_FEEDBACK_INSTRUCTION = "anBankFeedbackInstruction";
     public static final String FIELD_UPDATE_TIME = "updateTime";


     @Id
     private String orderNo;

     @Length(max = 45)
     private String bBranchName;

     @Length(max = 200)
     private String cMerchantName;

     @Length(max = 45)
     private String dAuthorizedOperator;

     @Length(max = 45)
     private String eMarketingPersonnelCode;

     @Length(max = 45)
     private String fRecommendedPersonnelCode;

     @Length(max = 45)
     private String gCustomerName;

     @Length(max = 4)
     private String hCardLastFourNumber;

     @Length(max = 5)
     private String iCertificatesLastFiveNumber;

     @Length(max = 20)
     private String jContactNumber;

     @Length(max = 20)
     private String kTelphone;

     @Length(max = 200)
     private String lDeliveryAddress;

     @Length(max = 6)
     private String mZipCode;

     @Length(max = 200)
     private String nInvoiceHeader;

     @Length(max = 45)
     private String oCommodityNumber;

     @Length(max = 45)
     private String pCommodityPrice;

     @Length(max = 45)
     private String qApplicationNumber;

     @Length(max = 45)
     private String rAuthorizationCode;

     @Length(max = 45)
     private String sProductNumber;

     @Length(max = 8)
     private String tCustomerOrderDate;

     @Length(max = 8)
     private String uActualDeliveryDate;

     @Length(max = 45)
     private String vCourierNumber;

     @Length(max = 45)
     private String wCourierServicesCompany;

     @Length(max = 45)
     private String xOverdueMark;

     @Length(max = 45)
     private String yDeliveryFileCategory;

     @Length(max = 45)
     private String zCardProduct;

     @Length(max = 45)
     private String aaNameOfAgent;

     @Length(max = 45)
     private String abTelphoneOfAgent;

     @Length(max = 45)
     private String acOrderStatus;

     @Length(max = 45)
     private String adBz;

     @Length(max = 8)
     private String alBankFeedbackTime;

     @Length(max = 45)
     private String amBankFeedbackType;

     @Length(max = 200)
     private String anBankFeedbackInstruction;

     private Date updateTime;


     public void setOrderNo(String orderNo){
         this.orderNo = orderNo;
     }

     public String getOrderNo(){
         return orderNo;
     }

     public void setBBranchName(String bBranchName){
         this.bBranchName = bBranchName;
     }

     public String getBBranchName(){
         return bBranchName;
     }

     public void setCMerchantName(String cMerchantName){
         this.cMerchantName = cMerchantName;
     }

     public String getCMerchantName(){
         return cMerchantName;
     }

     public void setDAuthorizedOperator(String dAuthorizedOperator){
         this.dAuthorizedOperator = dAuthorizedOperator;
     }

     public String getDAuthorizedOperator(){
         return dAuthorizedOperator;
     }

     public void setEMarketingPersonnelCode(String eMarketingPersonnelCode){
         this.eMarketingPersonnelCode = eMarketingPersonnelCode;
     }

     public String getEMarketingPersonnelCode(){
         return eMarketingPersonnelCode;
     }

     public void setFRecommendedPersonnelCode(String fRecommendedPersonnelCode){
         this.fRecommendedPersonnelCode = fRecommendedPersonnelCode;
     }

     public String getFRecommendedPersonnelCode(){
         return fRecommendedPersonnelCode;
     }

     public void setGCustomerName(String gCustomerName){
         this.gCustomerName = gCustomerName;
     }

     public String getGCustomerName(){
         return gCustomerName;
     }

     public void setHCardLastFourNumber(String hCardLastFourNumber){
         this.hCardLastFourNumber = hCardLastFourNumber;
     }

     public String getHCardLastFourNumber(){
         return hCardLastFourNumber;
     }

     public void setICertificatesLastFiveNumber(String iCertificatesLastFiveNumber){
         this.iCertificatesLastFiveNumber = iCertificatesLastFiveNumber;
     }

     public String getICertificatesLastFiveNumber(){
         return iCertificatesLastFiveNumber;
     }

     public void setJContactNumber(String jContactNumber){
         this.jContactNumber = jContactNumber;
     }

     public String getJContactNumber(){
         return jContactNumber;
     }

     public void setKTelphone(String kTelphone){
         this.kTelphone = kTelphone;
     }

     public String getKTelphone(){
         return kTelphone;
     }

     public void setLDeliveryAddress(String lDeliveryAddress){
         this.lDeliveryAddress = lDeliveryAddress;
     }

     public String getLDeliveryAddress(){
         return lDeliveryAddress;
     }

     public void setMZipCode(String mZipCode){
         this.mZipCode = mZipCode;
     }

     public String getMZipCode(){
         return mZipCode;
     }

     public void setNInvoiceHeader(String nInvoiceHeader){
         this.nInvoiceHeader = nInvoiceHeader;
     }

     public String getNInvoiceHeader(){
         return nInvoiceHeader;
     }

     public void setOCommodityNumber(String oCommodityNumber){
         this.oCommodityNumber = oCommodityNumber;
     }

     public String getOCommodityNumber(){
         return oCommodityNumber;
     }

     public void setPCommodityPrice(String pCommodityPrice){
         this.pCommodityPrice = pCommodityPrice;
     }

     public String getPCommodityPrice(){
         return pCommodityPrice;
     }

     public void setQApplicationNumber(String qApplicationNumber){
         this.qApplicationNumber = qApplicationNumber;
     }

     public String getQApplicationNumber(){
         return qApplicationNumber;
     }

     public void setRAuthorizationCode(String rAuthorizationCode){
         this.rAuthorizationCode = rAuthorizationCode;
     }

     public String getRAuthorizationCode(){
         return rAuthorizationCode;
     }

     public void setSProductNumber(String sProductNumber){
         this.sProductNumber = sProductNumber;
     }

     public String getSProductNumber(){
         return sProductNumber;
     }

     public void setTCustomerOrderDate(String tCustomerOrderDate){
         this.tCustomerOrderDate = tCustomerOrderDate;
     }

     public String getTCustomerOrderDate(){
         return tCustomerOrderDate;
     }

     public void setUActualDeliveryDate(String uActualDeliveryDate){
         this.uActualDeliveryDate = uActualDeliveryDate;
     }

     public String getUActualDeliveryDate(){
         return uActualDeliveryDate;
     }

     public void setVCourierNumber(String vCourierNumber){
         this.vCourierNumber = vCourierNumber;
     }

     public String getVCourierNumber(){
         return vCourierNumber;
     }

     public void setWCourierServicesCompany(String wCourierServicesCompany){
         this.wCourierServicesCompany = wCourierServicesCompany;
     }

     public String getWCourierServicesCompany(){
         return wCourierServicesCompany;
     }

     public void setXOverdueMark(String xOverdueMark){
         this.xOverdueMark = xOverdueMark;
     }

     public String getXOverdueMark(){
         return xOverdueMark;
     }

     public void setYDeliveryFileCategory(String yDeliveryFileCategory){
         this.yDeliveryFileCategory = yDeliveryFileCategory;
     }

     public String getYDeliveryFileCategory(){
         return yDeliveryFileCategory;
     }

     public void setZCardProduct(String zCardProduct){
         this.zCardProduct = zCardProduct;
     }

     public String getZCardProduct(){
         return zCardProduct;
     }

     public void setAaNameOfAgent(String aaNameOfAgent){
         this.aaNameOfAgent = aaNameOfAgent;
     }

     public String getAaNameOfAgent(){
         return aaNameOfAgent;
     }

     public void setAbTelphoneOfAgent(String abTelphoneOfAgent){
         this.abTelphoneOfAgent = abTelphoneOfAgent;
     }

     public String getAbTelphoneOfAgent(){
         return abTelphoneOfAgent;
     }

     public void setAcOrderStatus(String acOrderStatus){
         this.acOrderStatus = acOrderStatus;
     }

     public String getAcOrderStatus(){
         return acOrderStatus;
     }

     public void setAdBz(String adBz){
         this.adBz = adBz;
     }

     public String getAdBz(){
         return adBz;
     }

     public void setAlBankFeedbackTime(String alBankFeedbackTime){
         this.alBankFeedbackTime = alBankFeedbackTime;
     }

     public String getAlBankFeedbackTime(){
         return alBankFeedbackTime;
     }

     public void setAmBankFeedbackType(String amBankFeedbackType){
         this.amBankFeedbackType = amBankFeedbackType;
     }

     public String getAmBankFeedbackType(){
         return amBankFeedbackType;
     }

     public void setAnBankFeedbackInstruction(String anBankFeedbackInstruction){
         this.anBankFeedbackInstruction = anBankFeedbackInstruction;
     }

     public String getAnBankFeedbackInstruction(){
         return anBankFeedbackInstruction;
     }

     public void setUpdateTime(Date updateTime){
         this.updateTime = updateTime;
     }

     public Date getUpdateTime(){
         return updateTime;
     }
     
     public boolean isSame(Orders order){
    	 boolean flag =true;
    	 if(getOrderNo().equals(order.getOrderNo()))
    		 return false;
    	 if(getBBranchName().equals(order.getBBranchName()))
    		 return false;
    	 if(getCMerchantName().equals(order.getCMerchantName()))
    		 return false;
    	 if(getDAuthorizedOperator().equals(order.getDAuthorizedOperator()))
    		 return false;
    	 if(getEMarketingPersonnelCode().equals(order.getEMarketingPersonnelCode()))
    		 return false;
    	 if(getFRecommendedPersonnelCode().equals(order.getFRecommendedPersonnelCode()))
    		 return false;
    	 if(getGCustomerName().equals(order.getGCustomerName()))
    		 return false;
    	 if(getHCardLastFourNumber().equals(order.getHCardLastFourNumber()))
    		 return false;
    	 if(getICertificatesLastFiveNumber().equals(order.getICertificatesLastFiveNumber()))
    		 return false;
    	 if(getJContactNumber().equals(order.getJContactNumber()))
    		 return false;
    	 if(getKTelphone().equals(order.getKTelphone()))
    		 return false;
    	 if(getLDeliveryAddress().equals(order.getLDeliveryAddress()))
    		 return false;
    	 if(getMZipCode().equals(order.getMZipCode()))
    		 return false;
    	 if(getNInvoiceHeader().equals(order.getNInvoiceHeader()))
    		 return false;
    	 if(getOCommodityNumber().equals(order.getOCommodityNumber()))
    		 return false;
    	 if(getPCommodityPrice().equals(order.getPCommodityPrice()))
    		 return false;
    	 if(getQApplicationNumber().equals(order.getQApplicationNumber()))
    		 return false;
    	 if(getRAuthorizationCode().equals(order.getRAuthorizationCode()))
    		 return false;
    	 if(getSProductNumber().equals(order.getSProductNumber()))
    		 return false;
    	 if(getTCustomerOrderDate().equals(order.getTCustomerOrderDate()))
    		 return false;
    	 if(getUActualDeliveryDate().equals(order.getUActualDeliveryDate()))
    		 return false;
    	 if(getVCourierNumber().equals(order.getVCourierNumber()))
    		 return false;
    	 if(getWCourierServicesCompany().equals(order.getWCourierServicesCompany()))
    		 return false;
    	 if(getXOverdueMark().equals(order.getXOverdueMark()))
    		 return false;
    	 if(getYDeliveryFileCategory().equals(order.getYDeliveryFileCategory()))
    		 return false;
    	 if(getZCardProduct().equals(order.getZCardProduct()))
    		 return false;
    	 
    	 if(getAaNameOfAgent().equals(order.getAaNameOfAgent()))
    		 return false;
    	 if(getAbTelphoneOfAgent().equals(order.getAbTelphoneOfAgent()))
    		 return false;
    	 if(getAcOrderStatus().equals(order.getAcOrderStatus()))
    		 return false;
    	 if(getAdBz().equals(order.getAdBz()))
    		 return false;
    	 if(getAlBankFeedbackTime().equals(order.getAlBankFeedbackTime()))
    		 return false;
    	 if(getAmBankFeedbackType().equals(order.getAmBankFeedbackType()))
    		 return false;
    	 if(getAnBankFeedbackInstruction().equals(order.getAnBankFeedbackInstruction()))
    		 return false;
//    	 getCMerchantName
//    	 getDAuthorizedOperator
//    	 getEMarketingPersonnelCode
//    	 getFRecommendedPersonnelCode
//
//    	 getGCustomerName
//    	 getHCardLastFourNumber
//    	 getICertificatesLastFiveNumber
//    	 getJContactNumber
//    	 getKTelphone
//    	 getLDeliveryAddress
//    	 getMZipCode
//    	 getNInvoiceHeader
//    	 getOCommodityNumber
//    	 getPCommodityPrice
//    	 getQApplicationNumber
//    	 getRAuthorizationCode
//    	 getSProductNumber
//    	 getTCustomerOrderDate
//    	 getUActualDeliveryDate
//    	 getVCourierNumber
//    	 getWCourierServicesCompany
//    	 getXOverdueMark
//    	 getYDeliveryFileCategory
//    	 getZCardProduct
//
//    	 getAaNameOfAgent
//    	 getAbTelphoneOfAgent
//    	 getAcOrderStatus
//    	 getAdBz
//    	 getAlBankFeedbackTime
//    	 getAmBankFeedbackType
//    	 getAnBankFeedbackInstruction
    	 return flag;
     }

     }
