package com.huan.HTed.cado.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "cadoexcel_orders_item_log")
public class OrdersItemLog extends BaseDTO {

     public static final String FIELD_ORDER_NO = "orderNo";
     public static final String FIELD_AE_MODEL = "aeModel";
     public static final String FIELD_AF_ORDER_ATTRIBUTE = "afOrderAttribute";
     public static final String FIELD_AG_LOGISTICS_NAME = "agLogisticsName";
     public static final String FIELD_AH_LOGISTICS_NO = "ahLogisticsNo";
     public static final String FIELD_AI_DELIVERY_TIME = "aiDeliveryTime";
     public static final String FIELD_AJ_BZ = "ajBz";
     public static final String FIELD_AK_ORDER_BATCH = "akOrderBatch";
     public static final String FIELD_UPDATE_TIME = "updateTime";
     public static final String FIELD_UPDATE_PERSON = "updatePerson";


     @Length(max = 14)
     private String orderNo;

     @Length(max = 100)
     private String aeModel;

     @Length(max = 40)
     private String afOrderAttribute;

     @Length(max = 100)
     private String agLogisticsName;

     @Length(max = 40)
     private String ahLogisticsNo;

     @Length(max = 8)
     private String aiDeliveryTime;

     @Length(max = 200)
     private String ajBz;

     @Length(max = 8)
     private String akOrderBatch;

     private Date updateTime;
     
     @Length(max = 45)
     private String updateBz;
     
     private Long updatePerson;


     public void setOrderNo(String orderNo){
         this.orderNo = orderNo;
     }

     public String getOrderNo(){
         return orderNo;
     }

     public void setAeModel(String aeModel){
         this.aeModel = aeModel;
     }

     public String getAeModel(){
         return aeModel;
     }

     public void setAfOrderAttribute(String afOrderAttribute){
         this.afOrderAttribute = afOrderAttribute;
     }

     public String getAfOrderAttribute(){
         return afOrderAttribute;
     }

     public void setAgLogisticsName(String agLogisticsName){
         this.agLogisticsName = agLogisticsName;
     }

     public String getAgLogisticsName(){
         return agLogisticsName;
     }

     public void setAhLogisticsNo(String ahLogisticsNo){
         this.ahLogisticsNo = ahLogisticsNo;
     }

     public String getAhLogisticsNo(){
         return ahLogisticsNo;
     }

     public void setAiDeliveryTime(String aiDeliveryTime){
         this.aiDeliveryTime = aiDeliveryTime;
     }

     public String getAiDeliveryTime(){
         return aiDeliveryTime;
     }

     public void setAjBz(String ajBz){
         this.ajBz = ajBz;
     }

     public String getAjBz(){
         return ajBz;
     }

     public void setAkOrderBatch(String akOrderBatch){
         this.akOrderBatch = akOrderBatch;
     }

     public String getAkOrderBatch(){
         return akOrderBatch;
     }

     public void setUpdateTime(Date updateTime){
         this.updateTime = updateTime;
     }

     public Date getUpdateTime(){
         return updateTime;
     }
     
 	public String getUpdateBz() {
		return updateBz;
	}

	public void setUpdateBz(String updateBz) {
		this.updateBz = updateBz;
	}
	
	
	 public Long getUpdatePerson() {
		return updatePerson;
	}

	public void setUpdatePerson(Long updatePerson) {
		this.updatePerson = updatePerson;
	}

	public void cloneOrdersItem(OrdersItem ordersItem){
    	 this.setOrderNo(ordersItem.getOrderNo());
    	 this.setAeModel(ordersItem.getAeModel());
    	 this.setAfOrderAttribute(ordersItem.getAfOrderAttribute());
    	 this.setAgLogisticsName(ordersItem.getAgLogisticsName());
    	 this.setAhLogisticsNo(ordersItem.getAhLogisticsNo());
    	 this.setAiDeliveryTime(ordersItem.getAiDeliveryTime());
    	 this.setAjBz(ordersItem.getAjBz());
    	 this.setAkOrderBatch(ordersItem.getAkOrderBatch());
     }

     }
