package com.huan.HTed.cado.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "cadoexcel_orders_log")
public class OrdersLog extends BaseDTO {

     public static final String FIELD_ORDER_NO = "orderNo";
     public static final String FIELD_B_BRANCH_NAME = "bBranchName";
     public static final String FIELD_C_MERCHANT_NAME = "cMerchantName";
     public static final String FIELD_D_AUTHORIZED_OPERATOR = "dAuthorizedOperator";
     public static final String FIELD_E_MARKETING_PERSONNEL_CODE = "eMarketingPersonnelCode";
     public static final String FIELD_F_RECOMMENDED_PERSONNEL_CODE = "fRecommendedPersonnelCode";
     public static final String FIELD_G_CUSTOMER_NAME = "gCustomerName";
     public static final String FIELD_H_CARD_LAST_FOUR_NUMBER = "hCardLastFourNumber";
     public static final String FIELD_I_CERTIFICATES_LAST_FIVE_NUMBER = "iCertificatesLastFiveNumber";
     public static final String FIELD_J_CONTACT_NUMBER = "jContactNumber";
     public static final String FIELD_K_TELPHONE = "kTelphone";
     public static final String FIELD_L_DELIVERY_ADDRESS = "lDeliveryAddress";
     public static final String FIELD_M_ZIP_CODE = "mZipCode";
     public static final String FIELD_N_INVOICE_HEADER = "nInvoiceHeader";
     public static final String FIELD_O_COMMODITY_NUMBER = "oCommodityNumber";
     public static final String FIELD_P_COMMODITY_PRICE = "pCommodityPrice";
     public static final String FIELD_Q_APPLICATION_NUMBER = "qApplicationNumber";
     public static final String FIELD_R_AUTHORIZATION_CODE = "rAuthorizationCode";
     public static final String FIELD_S_PRODUCT_NUMBER = "sProductNumber";
     public static final String FIELD_T_CUSTOMER_ORDER_DATE = "tCustomerOrderDate";
     public static final String FIELD_U_ACTUAL_DELIVERY_DATE = "uActualDeliveryDate";
     public static final String FIELD_V_COURIER_NUMBER = "vCourierNumber";
     public static final String FIELD_W_COURIER_SERVICES_COMPANY = "wCourierServicesCompany";
     public static final String FIELD_X_OVERDUE_MARK = "xOverdueMark";
     public static final String FIELD_Y_DELIVERY_FILE_CATEGORY = "yDeliveryFileCategory";
     public static final String FIELD_Z_CARD_PRODUCT = "zCardProduct";
     public static final String FIELD_AA_NAME_OF_AGENT = "aaNameOfAgent";
     public static final String FIELD_AB_TELPHONE_OF_AGENT = "abTelphoneOfAgent";
     public static final String FIELD_AC_ORDER_STATUS = "acOrderStatus";
     public static final String FIELD_AD_BZ = "adBz";
     public static final String FIELD_AL_BANK_FEEDBACK_TIME = "alBankFeedbackTime";
     public static final String FIELD_AM_BANK_FEEDBACK_TYPE = "amBankFeedbackType";
     public static final String FIELD_AN_BANK_FEEDBACK_INSTRUCTION = "anBankFeedbackInstruction";
     public static final String FIELD_UPDATE_TIME = "updateTime";


     @Length(max = 14)
     private String orderNo;

     @Length(max = 45)
     private String bBranchName;

     @Length(max = 200)
     private String cMerchantName;

     @Length(max = 45)
     private String dAuthorizedOperator;

     @Length(max = 45)
     private String eMarketingPersonnelCode;

     @Length(max = 45)
     private String fRecommendedPersonnelCode;

     @Length(max = 45)
     private String gCustomerName;

     @Length(max = 4)
     private String hCardLastFourNumber;

     @Length(max = 5)
     private String iCertificatesLastFiveNumber;

     @Length(max = 20)
     private String jContactNumber;

     @Length(max = 20)
     private String kTelphone;

     @Length(max = 200)
     private String lDeliveryAddress;

     @Length(max = 6)
     private String mZipCode;

     @Length(max = 200)
     private String nInvoiceHeader;

     @Length(max = 45)
     private String oCommodityNumber;

     @Length(max = 45)
     private String pCommodityPrice;

     @Length(max = 45)
     private String qApplicationNumber;

     @Length(max = 45)
     private String rAuthorizationCode;

     @Length(max = 45)
     private String sProductNumber;

     @Length(max = 8)
     private String tCustomerOrderDate;

     @Length(max = 8)
     private String uActualDeliveryDate;

     @Length(max = 45)
     private String vCourierNumber;

     @Length(max = 45)
     private String wCourierServicesCompany;

     @Length(max = 45)
     private String xOverdueMark;

     @Length(max = 45)
     private String yDeliveryFileCategory;

     @Length(max = 45)
     private String zCardProduct;

     @Length(max = 45)
     private String aaNameOfAgent;

     @Length(max = 45)
     private String abTelphoneOfAgent;

     @Length(max = 45)
     private String acOrderStatus;

     @Length(max = 45)
     private String adBz;

     @Length(max = 8)
     private String alBankFeedbackTime;

     @Length(max = 45)
     private String amBankFeedbackType;

     @Length(max = 200)
     private String anBankFeedbackInstruction;

     private Date updateTime;
     
     @Length(max = 45)
     private String updateBz;


     public void setOrderNo(String orderNo){
         this.orderNo = orderNo;
     }

     public String getOrderNo(){
         return orderNo;
     }

     public void setBBranchName(String bBranchName){
         this.bBranchName = bBranchName;
     }

     public String getBBranchName(){
         return bBranchName;
     }

     public void setCMerchantName(String cMerchantName){
         this.cMerchantName = cMerchantName;
     }

     public String getCMerchantName(){
         return cMerchantName;
     }

     public void setDAuthorizedOperator(String dAuthorizedOperator){
         this.dAuthorizedOperator = dAuthorizedOperator;
     }

     public String getDAuthorizedOperator(){
         return dAuthorizedOperator;
     }

     public void setEMarketingPersonnelCode(String eMarketingPersonnelCode){
         this.eMarketingPersonnelCode = eMarketingPersonnelCode;
     }

     public String getEMarketingPersonnelCode(){
         return eMarketingPersonnelCode;
     }

     public void setFRecommendedPersonnelCode(String fRecommendedPersonnelCode){
         this.fRecommendedPersonnelCode = fRecommendedPersonnelCode;
     }

     public String getFRecommendedPersonnelCode(){
         return fRecommendedPersonnelCode;
     }

     public void setGCustomerName(String gCustomerName){
         this.gCustomerName = gCustomerName;
     }

     public String getGCustomerName(){
         return gCustomerName;
     }

     public void setHCardLastFourNumber(String hCardLastFourNumber){
         this.hCardLastFourNumber = hCardLastFourNumber;
     }

     public String getHCardLastFourNumber(){
         return hCardLastFourNumber;
     }

     public void setICertificatesLastFiveNumber(String iCertificatesLastFiveNumber){
         this.iCertificatesLastFiveNumber = iCertificatesLastFiveNumber;
     }

     public String getICertificatesLastFiveNumber(){
         return iCertificatesLastFiveNumber;
     }

     public void setJContactNumber(String jContactNumber){
         this.jContactNumber = jContactNumber;
     }

     public String getJContactNumber(){
         return jContactNumber;
     }

     public void setKTelphone(String kTelphone){
         this.kTelphone = kTelphone;
     }

     public String getKTelphone(){
         return kTelphone;
     }

     public void setLDeliveryAddress(String lDeliveryAddress){
         this.lDeliveryAddress = lDeliveryAddress;
     }

     public String getLDeliveryAddress(){
         return lDeliveryAddress;
     }

     public void setMZipCode(String mZipCode){
         this.mZipCode = mZipCode;
     }

     public String getMZipCode(){
         return mZipCode;
     }

     public void setNInvoiceHeader(String nInvoiceHeader){
         this.nInvoiceHeader = nInvoiceHeader;
     }

     public String getNInvoiceHeader(){
         return nInvoiceHeader;
     }

     public void setOCommodityNumber(String oCommodityNumber){
         this.oCommodityNumber = oCommodityNumber;
     }

     public String getOCommodityNumber(){
         return oCommodityNumber;
     }

     public void setPCommodityPrice(String pCommodityPrice){
         this.pCommodityPrice = pCommodityPrice;
     }

     public String getPCommodityPrice(){
         return pCommodityPrice;
     }

     public void setQApplicationNumber(String qApplicationNumber){
         this.qApplicationNumber = qApplicationNumber;
     }

     public String getQApplicationNumber(){
         return qApplicationNumber;
     }

     public void setRAuthorizationCode(String rAuthorizationCode){
         this.rAuthorizationCode = rAuthorizationCode;
     }

     public String getRAuthorizationCode(){
         return rAuthorizationCode;
     }

     public void setSProductNumber(String sProductNumber){
         this.sProductNumber = sProductNumber;
     }

     public String getSProductNumber(){
         return sProductNumber;
     }

     public void setTCustomerOrderDate(String tCustomerOrderDate){
         this.tCustomerOrderDate = tCustomerOrderDate;
     }

     public String getTCustomerOrderDate(){
         return tCustomerOrderDate;
     }

     public void setUActualDeliveryDate(String uActualDeliveryDate){
         this.uActualDeliveryDate = uActualDeliveryDate;
     }

     public String getUActualDeliveryDate(){
         return uActualDeliveryDate;
     }

     public void setVCourierNumber(String vCourierNumber){
         this.vCourierNumber = vCourierNumber;
     }

     public String getVCourierNumber(){
         return vCourierNumber;
     }

     public void setWCourierServicesCompany(String wCourierServicesCompany){
         this.wCourierServicesCompany = wCourierServicesCompany;
     }

     public String getWCourierServicesCompany(){
         return wCourierServicesCompany;
     }

     public void setXOverdueMark(String xOverdueMark){
         this.xOverdueMark = xOverdueMark;
     }

     public String getXOverdueMark(){
         return xOverdueMark;
     }

     public void setYDeliveryFileCategory(String yDeliveryFileCategory){
         this.yDeliveryFileCategory = yDeliveryFileCategory;
     }

     public String getYDeliveryFileCategory(){
         return yDeliveryFileCategory;
     }

     public void setZCardProduct(String zCardProduct){
         this.zCardProduct = zCardProduct;
     }

     public String getZCardProduct(){
         return zCardProduct;
     }

     public void setAaNameOfAgent(String aaNameOfAgent){
         this.aaNameOfAgent = aaNameOfAgent;
     }

     public String getAaNameOfAgent(){
         return aaNameOfAgent;
     }

     public void setAbTelphoneOfAgent(String abTelphoneOfAgent){
         this.abTelphoneOfAgent = abTelphoneOfAgent;
     }

     public String getAbTelphoneOfAgent(){
         return abTelphoneOfAgent;
     }

     public void setAcOrderStatus(String acOrderStatus){
         this.acOrderStatus = acOrderStatus;
     }

     public String getAcOrderStatus(){
         return acOrderStatus;
     }

     public void setAdBz(String adBz){
         this.adBz = adBz;
     }

     public String getAdBz(){
         return adBz;
     }

     public void setAlBankFeedbackTime(String alBankFeedbackTime){
         this.alBankFeedbackTime = alBankFeedbackTime;
     }

     public String getAlBankFeedbackTime(){
         return alBankFeedbackTime;
     }

     public void setAmBankFeedbackType(String amBankFeedbackType){
         this.amBankFeedbackType = amBankFeedbackType;
     }

     public String getAmBankFeedbackType(){
         return amBankFeedbackType;
     }

     public void setAnBankFeedbackInstruction(String anBankFeedbackInstruction){
         this.anBankFeedbackInstruction = anBankFeedbackInstruction;
     }

     public String getAnBankFeedbackInstruction(){
         return anBankFeedbackInstruction;
     }

     public void setUpdateTime(Date updateTime){
         this.updateTime = updateTime;
     }

     public Date getUpdateTime(){
         return updateTime;
     }

	public String getUpdateBz() {
		return updateBz;
	}

	public void setUpdateBz(String updateBz) {
		this.updateBz = updateBz;
	}
     
     public void cloneOrders(Orders order){
    	 this.setOrderNo(order.getOrderNo());
    	 this.setBBranchName(order.getBBranchName());
    	 this.setCMerchantName(order.getCMerchantName());
    	 this.setDAuthorizedOperator(order.getDAuthorizedOperator());
    	 this.setEMarketingPersonnelCode(order.getEMarketingPersonnelCode());
    	 this.setFRecommendedPersonnelCode(order.getFRecommendedPersonnelCode());
    	 this.setGCustomerName(order.getGCustomerName());
    	 this.setHCardLastFourNumber(order.getHCardLastFourNumber());
    	 this.setICertificatesLastFiveNumber(order.getICertificatesLastFiveNumber());
    	 this.setJContactNumber(order.getJContactNumber());
    	 this.setKTelphone(order.getKTelphone());
    	 this.setLDeliveryAddress(order.getLDeliveryAddress());
    	 this.setMZipCode(order.getMZipCode());
    	 this.setNInvoiceHeader(order.getNInvoiceHeader()); 
    	 this.setOCommodityNumber(order.getOCommodityNumber());
    	 this.setPCommodityPrice(order.getPCommodityPrice());
    	 this.setQApplicationNumber(order.getQApplicationNumber());
    	 this.setRAuthorizationCode(order.getRAuthorizationCode());
    	 this.setSProductNumber(order.getSProductNumber());
    	 this.setTCustomerOrderDate(order.getTCustomerOrderDate());
    	 this.setUActualDeliveryDate(order.getUActualDeliveryDate());
    	 this.setVCourierNumber(order.getVCourierNumber());
    	 this.setWCourierServicesCompany(order.getWCourierServicesCompany());
    	 this.setXOverdueMark(order.getXOverdueMark());
    	 this.setYDeliveryFileCategory(order.getYDeliveryFileCategory());
    	 this.setZCardProduct(order.getZCardProduct());
    	 
    	 this.setAaNameOfAgent(order.getAaNameOfAgent());
    	 this.setAbTelphoneOfAgent(order.getAbTelphoneOfAgent());
    	 this.setAcOrderStatus(order.getAcOrderStatus());
    	 this.setAdBz(order.getAdBz());
    	 this.setAlBankFeedbackTime(order.getAlBankFeedbackTime());
    	 this.setAmBankFeedbackType(order.getAmBankFeedbackType());
    	 this.setAnBankFeedbackInstruction(order.getAnBankFeedbackInstruction());
    	
    	 
//    	 getAaNameOfAgent
//    	 getAbTelphoneOfAgent
//    	 getAcOrderStatus
//    	 getAdBz
//    	 getAlBankFeedbackTime
//    	 getAmBankFeedbackType
//    	 getAnBankFeedbackInstruction
     }

     }
